version: '3.8'

services:
  nginx-rtmp:
    build: ./nginx
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./hls:/mnt/hls  

  node-server:
    build: ./server
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - nginx-rtmp
